# _config.yml
title: "Runes780 Blog"
description: "A modern personal blog powered by Jekyll on GitHub Pages"
theme: minima  # 也可在此指定其他主题
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
markdown: kramdown

# 自定义导航菜单，可在模板或layout中引用 site.data.navigation
# 需要在 _data 目录下添加 navigation.yml
